---
title: "Proba de transitions MDP"
author: "Kevin"
date: "30 août 2019"
output:
  pdf_document: default
  html_document: default
  always_allow_html: yes
---

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE)
library(trackeR)

source("../Functions/k-means.R")
source("../Functions/troncons.R")
```

# Importation data CSV
```{r, include=TRUE}
fp <- list.files("../../Data/DataCSV/Urutty", full.names = TRUE)

sessions <- list()
for(k in 1:length(fp)){
  if(substr(fp[k],nchar(fp[k])-2, nchar(fp[k])) == "csv"){
    dftemp <- read.csv(fp[k])
    sessions[[k]] <- dftemp # Attention si on a pas des fichiers CSV
  }
}

print(sessions[[2]])

nbSessions <- length(sessions)
print(paste("nb of running sessions =", nbSessions))
```

## Traitement des données avec kmeans par session (une course pour commencer)
```{r, include=TRUE}
i <- 1
run <- sessions[[i]]
runCleaned <- preProcessDataForSectionCSV(run)
troncons <- sliceSession(runCleaned)
  
# Remove "distance" variable
# troncons <- troncons[, -1]
n <- dim(troncons)[1]
p <- dim(troncons)[2]

troncons.norm <- sapply(troncons, scale)
row.names(troncons.norm) <- row.names(troncons) 

km <- kmeans(troncons.norm, 3)
  
indexTroncons <- 1:n
plot(indexTroncons, troncons$speed, main = paste("speed each section for session", i), type = "p", pch = 20, col = km$cluster)

plot(indexTroncons, troncons$heart_rate, main = paste("heart-rate each section for session", i), type = "p", pch = 20, col = km$cluster)

plot(indexTroncons, troncons$cadence_running, main = paste("cadence running each section for session", i), type = "p", pch = 20, col = km$cluster)

plot(indexTroncons, troncons$elevation, main = paste("elevation each section for session", i), type = "p", pch = 20, col = km$cluster)
```

## Les probabilités de transitions ()
```{r, include=TRUE}
cluster <- km$cluster
cluster

set.seed(123)
P <- matrix(0, 3, 3)
for (i in 1:nbSessions) {
  # i <- 1
  run <- sessions[[i]]
  runCleaned <- preProcessDataForSectionCSV(run)
  troncons <- sliceSession(runCleaned)
  # Remove "distance" variable
  troncons <- troncons[, -1]
  n <- dim(troncons)[1]
  p <- dim(troncons)[2]
  
  troncons.norm <- sapply(troncons, scale)
  row.names(troncons.norm) <- row.names(troncons)
  
  km <- kmeans(troncons.norm, 3)
  cluster <- km$cluster

  indexTroncons <- 1:n
  # plot(indexTroncons, troncons$speed, main = paste("speed each section for session", i), type = "p", pch = 20, col = km$cluster)

  for(j in 1:(n-1)) {
    P[cluster[j], cluster[j+1]] <- P[cluster[j], cluster[j+1]] + 1
  }

}

for (i in 1:3) {
  P[i,] <- P[i,]/sum(P[i,])
}
P
```



30/08/2019
# Les courses de 10 km + kmeans
```{r, include=TRUE}
set.seed(123)
k <- 3

allSessions <- data.frame()
allSessionsScaled <- data.frame()
for (i in 1:nbSessions) {
  run <- sessions[[i]]

  runCleaned <- preProcessDataForSectionCSV(run)
  troncons <- sliceSession(runCleaned)
  troncons.norm <- sapply(troncons, scale)
  row.names(troncons.norm) <- row.names(troncons) 
  
  allSessions <- rbind(allSessions, cbind(session = rep(i, dim(troncons)[1]), troncons))
  allSessionsScaled <- rbind(allSessionsScaled, cbind(session = rep(i, dim(troncons)[1]), troncons.norm))
}

sizesSessions <- vector(mode = "numeric", length = nbSessions)
for (i in 1:nbSessions) {
  sizesSessions[i] <- nrow(allSessions[allSessions$session == i, ])
}
hist(sizesSessions, breaks = 28, col = 6)
print(sizesSessions)

# Les courses de 10 km
indices10km <- which(sizesSessions == 10)
print(indices10km)
nbSessions10km <- length(indices10km)

all10kmSessionsScaled <- data.frame()
for (i in 1:nbSessions10km) {
  all10kmSessionsScaled <- rbind(all10kmSessionsScaled, allSessionsScaled[allSessionsScaled$session == indices10km[i], ])
}

print(all10kmSessionsScaled)
  
km <- kmeans(all10kmSessionsScaled[,-1], k)
print(km$centers)

for (i in 1:nbSessions10km) {
  plot(all10kmSessionsScaled[all10kmSessionsScaled$session == indices10km[i], ]$speed, main = paste("speed each section for session", indices10km[i]), type = "p", pch = 20, col = km$cluster[all10kmSessionsScaled$session == indices10km[i]], xlab = "troncon", ylab = "speed")
}

clusters10kmSessions_allSession <- list()
for (i in 1:nbSessions10km) {
  clusters10kmSessions_allSession[[indices10km[i]]] <- km$cluster[all10kmSessionsScaled$session == indices10km[i]]
}


# Pour fonction matrice de transition
## Les sessions de 10 km
tenKmSessions <- list()
for (i in 1:nbSessions10km) {
  tenKmSessions[[i]] <- allSessions[allSessions$session == indices10km[i], ]
}
## Les clusters pour les courses de 10 km
clusters10kmSessions <- list()
for (i in 1:nbSessions10km) {
  clusters10kmSessions[[i]] <- clusters10kmSessions_allSession[[indices10km[[i]]]]
}

```

# Matrice de transition pour chaque action
```{r, include=TRUE}
actions <- c(150, 200, 225, 250, 275, 300)
actions <- c(200, 250, 300)
print(actions)

# Input : the running sessions in sections, the clusters of each section, the number of clusters and the actions in the MDP
# Output : List of the transition matrix for each action
transitionMatrix <- function(sessions, clusters, nbClusters, actions) {
  nbSessions <- length(sessions)
  nbActions <- length(actions)

  # Initialisation of transition matrix
  tMatrix <- list()
  for (i in 1:nbActions) {
    tMatrix[[i]] <- matrix(0, nbClusters, nbClusters)
  } 
  
  for (i in 1:nbSessions) {
    troncons <- sessions[[i]]
    n <- dim(troncons)[1]
    cluster <- clusters[[i]]
    
    for(j in 1:(n-1)) {
      # Determining which action ?
      action <- which.min(abs(actions - troncons$speed[j]))
      tMatrix[[action]][cluster[j], cluster[j+1]] <- tMatrix[[action]][cluster[j], cluster[j+1]] + 1
    }
  }

  # Transform in probabilities
  for (i in 1:nbActions) {
    for (j in 1:nbClusters) {
      s <- sum(tMatrix[[i]][j,])
      if (s == 0) {
        tMatrix[[i]][j,] <- 0
      }
      else {
        tMatrix[[i]][j,] <- tMatrix[[i]][j,]/s
      }
    }
  }
  return(tMatrix)
}
P <- transitionMatrix(tenKmSessions, clusters10kmSessions, 3, actions)
print(P)
```


# Matrice de transition les courses de X km
```{r, include=TRUE}
set.seed(123)
# Input : the running sessions in sections, actions in the MDP, the number of clusters and the distance of each section
# Output : List of the transition matrix for each action
transitionMatrixForSessionOfXkm <- function(sessions, actions, nbCluster, sessionDistance) {
  nbSessions <- length(sessions)
  
  allSessions <- data.frame()
  allSessionsScaled <- data.frame()
  for (i in 1:nbSessions) {
    run <- sessions[[i]]
    runCleaned <- preProcessDataForSectionCSV(run)
    troncons <- sliceSession(runCleaned)
    troncons.norm <- sapply(troncons, scale)
    row.names(troncons.norm) <- row.names(troncons) 
    
    allSessions <- rbind(allSessions, cbind(session = rep(i, dim(troncons)[1]), troncons))
    allSessionsScaled <- rbind(allSessionsScaled, cbind(session = rep(i, dim(troncons)[1]), troncons.norm))
  }
  
  # Les courses de 10 km
  sizesSessions <- vector(mode = "numeric", length = nbSessions)
  for (i in 1:nbSessions) {
    sizesSessions[i] <- nrow(allSessions[allSessions$session == i, ])
  }
  # hist(sizesSessions, breaks = 28, col = 6)
  indicesXkm <- which(sizesSessions == sessionDistance)
  print(paste("Sessions of", sessionDistance, "km :"))
  print(indicesXkm)
  nbSessionsXkm <- length(indicesXkm)
  
  allXkmSessions <- data.frame()
  allXkmSessionsScaled <- data.frame()
  for (i in 1:nbSessionsXkm) {
    allXkmSessions <- rbind(allXkmSessions, allSessions[allSessions$session == indicesXkm[i], ])
    allXkmSessionsScaled <- rbind(allXkmSessionsScaled, allSessionsScaled[allSessionsScaled$session == indicesXkm[i], ])
  }
  
  # kmeans
  km <- kmeans(allXkmSessionsScaled[,-1], nbCluster)
  # The centers (unscale)
  centers <- km$centers
  meanAll <- sapply(allXkmSessions, mean)[-1]
  sdAll <- sapply(allXkmSessions, sd)[-1]
  for (i in 1:ncol(km$centers)) {
    centers[,i] <- centers[,i] * sdAll[i] + meanAll[i]
  }
  print(paste("kmeans - centers :"))
  print(centers)
  
  # for (i in 1:nbSessions10km) {
  #   plot(allXkmSessionsScaled[allXkmSessionsScaled$session == indicesXkm[i], ]$speed, main = paste("speed each section for session", indicesXkm[i]), type = "p", pch = 20, col = km$cluster[allXkmSessionsScaled$session == indicesXkm[i]], xlab = "troncon", ylab = "speed")
  # }
  
  clustersXkmSessions <- list()
  for (i in 1:nbSessionsXkm) {
    clustersXkmSessions[[i]]<- km$cluster[allXkmSessionsScaled$session == indicesXkm[i]]
  }
  
  # Pour fonction matrice de transition
  ## Les sessions de X km
  XKmSessions <- list()
  for (i in 1:nbSessionsXkm) {
    XKmSessions[[i]] <- allSessions[allSessions$session == indicesXkm[i], ]
  }
  
  P <- transitionMatrix(XKmSessions, clustersXkmSessions, nbCluster, actions)
  return(P)
}

source("./MDP.R")
set.seed(123)
actions <- c(200, 250, 300, 450)
nbCluster <- 3
distanceSession <- 10

P <- transitionMatrixForSessionOfXkm(sessions, actions, nbCluster, distanceSession)
print(P)
```
